Models/Sede.cs
using System;
using System.Collections.Generic;

namespace AppReportes.Models
{
    public partial class Sede
    {
        public Sede()
        {
            Cita = new HashSet<Cita>();
            Doctor = new HashSet<Doctor>();
        }

        public int Iidsede { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}

Controllers/SedeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AppReportes.Clases;
using AppReportes.Models;

namespace AppReportes.Controllers
{
    public class SedeController : BaseController
    {
        public static List<SedeCLS> lista;
        public string Error = "Ha ocurrido una excepción, favor intente de nuevo";

        //Este metodo nos descarga el excel, word y pdf
        public FileResult Exportar(string[] nombreProp, string tipoReporte)
        {
            //string[] cabeceras = { "ID de especialidad", "Nombre", "Descripcion" };
            //string[] nombreProp = { "IdEspecialidad", "Nombre", "Descripcion" };
            if (tipoReporte == "Excel")
            {
                byte[] buffer = ExportarExcelDatos(nombreProp, lista);
                return File(buffer,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }
            else if (tipoReporte == "PDF")
            {
                byte[] buffer = ExportarPDFDatos(nombreProp, lista);
                return File(buffer,
                    "application/pdf");
            }
            else if (tipoReporte == "Word")
            {
                byte[] buffer = ExportarWordDatos(nombreProp, lista);
                return File(buffer,
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
            }
            return null;
        }

        public IActionResult Index(SedeCLS oSedeCLS)
        {
            List<SedeCLS> listaSedes = new List<SedeCLS>();
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    if (oSedeCLS.NombreSede == "" || oSedeCLS.NombreSede == null)//Filtro sensitivo
                    {
                        listaSedes = (from sede in db.Sede
                                      where sede.Bhabilitado == 1
                                      select new SedeCLS
                                      {
                                          IdSede = sede.Iidsede,
                                          NombreSede = sede.Nombre,
                                          Direccion = sede.Direccion
                                      }).ToList();
                        ViewBag.NombreSede = "";
                    }
                    else
                    {
                        listaSedes = (from sede in db.Sede
                                      where sede.Bhabilitado == 1
                                      && sede.Nombre.Contains(oSedeCLS.NombreSede)
                                      select new SedeCLS
                                      {
                                          IdSede = sede.Iidsede,
                                          NombreSede = sede.Nombre,
                                          Direccion = sede.Direccion
                                      }).ToList();
                        ViewBag.NombreSede = oSedeCLS.NombreSede;
                    }
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            lista = listaSedes;
            return View(listaSedes);
        }

        public IActionResult Editar(int id)
        {
            SedeCLS oSedeCLS = new SedeCLS();
            try
            {                
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    oSedeCLS = (from sede in db.Sede
                                where sede.Iidsede == id
                                select new SedeCLS
                                {
                                    IdSede = sede.Iidsede,
                                    NombreSede = sede.Nombre,
                                    Direccion = sede.Direccion
                                }).First();
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            return View(oSedeCLS);
        }

        [HttpPost]
        public IActionResult Guardar(SedeCLS oSedeCLS)
        {
            string NombreVista = "";

            try
            {
                if (oSedeCLS.IdSede == 0) NombreVista = "Agregar";
                else NombreVista = "Editar";

                if(!ModelState.IsValid)
                {
                    return View(NombreVista, oSedeCLS);
                }
                else
                {
                    using(BDHospitalContext db = new BDHospitalContext())
                    {
                        if(oSedeCLS.IdSede != 0)
                        {
                            Sede sede = db.Sede.Where(x => x.Iidsede == oSedeCLS.IdSede).First();
                            sede.Nombre = oSedeCLS.NombreSede;
                            sede.Direccion = oSedeCLS.Direccion;
                            db.SaveChanges();
                        }
                        
                    }
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            return RedirectToAction("Index");
        }

        //Eliminación lógica
        [HttpPost]
        public IActionResult Eliminar(int IdSede)
        {
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    Sede oSede = db.Sede.Where(x => x.Iidsede == IdSede).First();
                    oSede.Bhabilitado = 0;//Eliminación lógica
                    db.SaveChanges();
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Sede/Editar.cshtml
@model AppReportes.Clases.SedeCLS

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Guardar" asp-controller="Sede" id="frmEnviar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSede"  class="control-label"></label>
                <input asp-for="IdSede" checked class="form-control" readonly/>
                <span asp-validation-for="IdSede" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreSede" class="control-label"></label>
                <input asp-for="NombreSede" checked class="form-control" />
                <span asp-validation-for="NombreSede" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" checked class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Guardar" class="btn btn-primary" onclick="Abrir()"/>
                <a asp-action="Index" class="btn btn-danger">Regresar</a>
            </div>
        </form>
    </div>
</div>

<script src="~/js/generic.js"></script>
<script src="~/js/sweetalert.js"></script>
<script>
    function Abrir() {
        mostrarModal().then(res => {
            if (res.value) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Views/Sede/Index.cshtml
@model IEnumerable<AppReportes.Clases.SedeCLS>

@{
    ViewData["Title"] = "Index";
    string nombreSede = ViewBag.NombreSede;
}

@*Filtro sensitivo*@
<input type="button" value="Exportar Excel" class=" btn btn-success" onclick="ExportarExcel()" />
<input type="button" value="Exportar PDF" class=" btn btn-danger" onclick="ExportarPdf()" />
<input type="button" value="Exportar Word" class=" btn btn-primary" onclick="ExportarWord()" />

<form id="frmEnviar" asp-controller="Sede" asp-action="Index" class="mb-2" method="post">
    <label>Ingrese nombre de sede</label>
    <input type="text" class="form form-control" name="NombreSede"
           onkeyup="Buscar()" value="@nombreSede" />
</form>

<form asp-controller="Sede" asp-action="Exportar" id="frmReporte">
    <table class="table" id="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(x => x.IdSede)
                </th>
                <th>
                    @Html.DisplayNameFor(x => x.NombreSede)
                </th>
                <th>
                    @Html.DisplayNameFor(x => x.Direccion)
                </th>               
            </tr>
            <tr id="tcheck">
                <th>
                    <input type="checkbox" checked name="nombreProp" value="IdSede" />
                    <input type="hidden" name="tipoReporte" id="tipoReporte" />
                </th>
                <th>
                    <input type="checkbox" checked name="nombreProp" value="NombreSede" />
                </th>
                <th>
                    <input type="checkbox" checked name="nombreProp" value="Direccion" />
                </th>
                <th><strong>Operaciones</strong></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdSede)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreSede)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Direccion)
                    </td>
                    <td>
                        <i class="fa fa-trash btn btn-danger" aria-hidden="true"
                           onclick="EliminarSede(@item.IdSede)">
                        </i>
                        <a class="fa fa-edit btn btn-primary" aria-hidden="true"
                           asp-controller="Sede" asp-action="Editar"
                           asp-route-id="@item.IdSede">
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

<form asp-action="Eliminar" asp-controller="Sede" method="post" id="frmEliminarSede">
    <input type="hidden" id="txtSede" name="IdSede"/>
</form>

<script src="~/js/generic.js"></script>
<script src="~/js/sweetalert.js"></script>
<script>
    function Buscar() {
        document.getElementById("frmEnviar").submit();
    }

    //Eliminación lógica
    function EliminarSede(IdSede) {
        document.getElementById("txtSede").value = IdSede;
        mostrarModal().then(res => {
            if (res.value) {//Si hace click en aceptar                
                var frmEliminarSede = document.getElementById("frmEliminarSede");
                frmEliminarSede.submit();
            }
        })
    }
</script>