Models/Especialidad.cs
using System;
using System.Collections.Generic;

namespace AppReportes.Models
{
    public partial class Especialidad
    {
        public Especialidad()
        {
            Doctor = new HashSet<Doctor>();
        }

        public int Iidespecialidad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}

Controllers/EspecialidadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AppReportes.Clases;
using AppReportes.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppReportes.Controllers
{
    public class EspecialidadController : BaseController
    {
        public static List<EspecialidadCLS> lista;
        public string Error = "Ha ocurrido un error en tiempo de ejecución, por favor espere";

        //Este metodo nos descarga el excel, word y pdf
        public FileResult Exportar(string[] nombreProp, string tipoReporte)
        {
            //string[] cabeceras = { "ID de especialidad", "Nombre", "Descripcion" };
            //string[] nombreProp = { "IdEspecialidad", "Nombre", "Descripcion" };
            if(tipoReporte == "Excel")
            {
                byte[] buffer = ExportarExcelDatos(nombreProp, lista);
                return File(buffer,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }          
            else if(tipoReporte == "Word")
            {
                byte[] buffer = ExportarWordDatos(nombreProp, lista);
                return File(buffer, 
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
            }           
            return null;
        }

        public string ExportarDatosPDF(string[] nombreProp)
        {
            byte[] buffer = ExportarPDFDatos(nombreProp, lista);
            string cadena = Convert.ToBase64String(buffer);
            cadena = "data:application/pdf;base64," + cadena;
            return cadena;
        }
        
        public IActionResult Index(EspecialidadCLS especialidadCLS)
        {
            List<EspecialidadCLS> listaEspecialidad = new List<EspecialidadCLS>();
            using (BDHospitalContext db = new BDHospitalContext())
            {                
                try
                {
                    //Condición para filtrar
                    if (especialidadCLS.Nombre == null || especialidadCLS.Nombre == " ")
                    {
                        listaEspecialidad = (from especialidad in db.Especialidad
                                             where especialidad.Bhabilitado == 1
                                             select new EspecialidadCLS
                                             {
                                                 IdEspecialidad = especialidad.Iidespecialidad,
                                                 Nombre = especialidad.Nombre,
                                                 Descripcion = especialidad.Descripcion
                                             }).ToList();
                        ViewBag.NombreEspecialidad = "";
                    }
                    else
                    {
                        listaEspecialidad = (from especialidad in db.Especialidad
                                             where especialidad.Bhabilitado == 1
                                             && especialidad.Nombre.Contains(especialidadCLS.Nombre)
                                             select new EspecialidadCLS
                                             {
                                                 IdEspecialidad = especialidad.Iidespecialidad,
                                                 Nombre = especialidad.Nombre,
                                                 Descripcion = especialidad.Descripcion
                                             }).ToList();
                        ViewBag.NombreEspecialidad = especialidadCLS.Nombre;//Para guardar la busqueda
                    }
                }
                catch (Exception e)
                {
                    Error = e.Message;
                    throw e;
                }                
            }
            lista = listaEspecialidad;
            return View(listaEspecialidad);
        } 

        public IActionResult Agregar()
        {
            return View();
        }

        //Eliminación lógica
        [HttpPost]
        public IActionResult Eliminar(int IdEspecialidad)
        {           
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    Especialidad oEspecialidad = db.Especialidad
                        .Where(x => x.Iidespecialidad == IdEspecialidad).First();
                    oEspecialidad.Bhabilitado = 0;//Se cambia de estado y no se elimina
                    db.SaveChanges();
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
                throw e;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Agregar(EspecialidadCLS especialidadCLS)
        {
            string NombreVista = "";
            int nveces = 0;
            try
            {
                if (especialidadCLS.IdEspecialidad == 0) NombreVista = "Agregar";
                else NombreVista = "Editar";

                using(BDHospitalContext db = new BDHospitalContext())
                {
                    //Se analiza cuantas veces el nombre de la especialidad se repite en la DB
                    if(especialidadCLS.IdEspecialidad == 0)//Solo afecta al metodo Agregar                        
                    nveces = db.Especialidad
                        .Where(x => x.Nombre.ToUpper().Trim() 
                        == especialidadCLS.Nombre.ToUpper().Trim()).Count();//Para que la comparacion sea todo en mayuscula en DB

                    if(!ModelState.IsValid || nveces >= 1)
                    {
                        if (nveces >= 1) especialidadCLS.MensajeError = "El nombre de la especialidad ya existe";
                        return View(NombreVista, especialidadCLS);
                    }
                    else
                    {
                        if(especialidadCLS.IdEspecialidad == 0)
                        {
                            Especialidad objeto = new Especialidad
                            {
                                Nombre = especialidadCLS.Nombre,
                                Descripcion = especialidadCLS.Descripcion,
                                Bhabilitado = 1
                            };
                            db.Especialidad.Add(objeto);
                            db.SaveChanges();
                        } 
                        else
                        {
                            Especialidad objeto = db.Especialidad
                                .Where(p => p.Iidespecialidad == especialidadCLS.IdEspecialidad).First();
                            objeto.Nombre = especialidadCLS.Nombre;
                            objeto.Descripcion = especialidadCLS.Descripcion;
                            db.SaveChanges();
                        }
                    }
                }
            }
            catch(Exception e)
            {
                return View(NombreVista, especialidadCLS);
                throw e;
            }          
            return RedirectToAction("Index");
        }
           
        [HttpGet]
        public IActionResult Editar(int id)
        {
            EspecialidadCLS oEspecialidadCLS = new EspecialidadCLS();
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    oEspecialidadCLS = (from e in db.Especialidad
                                        where e.Iidespecialidad == id
                                        select new EspecialidadCLS
                                        {
                                            IdEspecialidad = e.Iidespecialidad,
                                            Nombre = e.Nombre,
                                            Descripcion = e.Descripcion
                                        }).First();
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
                throw e;
            }
            return View(oEspecialidadCLS);
        }
    }
}

Views/Especialidad/Agregar.cshtml
@using AppReportes.Clases;
@model EspecialidadCLS;
@{
    ViewData["Title"] = "Agregar";
}

<h1>Crear una especialidad</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Agregar" method="post" id="frmEnviar">
            <div class="form-group">
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
                @if(Model != null && Model.MensajeError != null && Model.MensajeError != "")
                {
                    <p class="text-danger">El nombre de la especialidad ya existe</p>
                }
            </div>
            <div class="form-group">
                <label asp-for="Descripcion"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Aceptar" onclick="abrirModal()"
                       class="btn btn-primary" />
                <a asp-action="Index" asp-controller="Especialidad"
                   class="btn btn-danger">
                    Regresar
                </a>
            </div>
        </form>
    </div>
</div>
<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script>
    function abrirModal() {
        mostrarModal().then((result) => {
            if (result.value) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Views/Especialidad/Editar.cshtml
@using AppReportes.Clases;
@model EspecialidadCLS;
@{
    ViewData["Title"] = "Agregar";
}

<h1>Editar una especialidad</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Editar" method="post" id="frmEnviar">
            <div class="form-group">
                <label asp-for="IdEspecialidad"></label>
                <input asp-for="IdEspecialidad" class="form-control" />
                <span asp-validation-for="IdEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Aceptar" onclick="abrirModal()"
                       class="btn btn-primary" />
                <a asp-action="Index" asp-controller="Especialidad"
                   class="btn btn-danger">
                    Regresar
                </a>
            </div>
        </form>
    </div>
</div>
<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script>
    function abrirModal() {
        mostrarModal().then((result) => {
            if (result.value) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Views/Especialidad/Index.cshtml
@using AppReportes.Clases;
@model IEnumerable<EspecialidadCLS>
@{
    ViewData["Title"] = "Index";
    string nombreEspecialidad = ViewBag.NombreEspecialidad;
}

<a class="btn btn-secondary" asp-controller="Especialidad" asp-action="Agregar">
    <strong>Agregar</strong>
</a>
<input type="button" value="Exportar Excel" class=" btn btn-success" 
       onclick="ExportarExcel()"/>
<input type="button" value="Exportar PDF" class=" btn btn-danger" 
       onclick="ExportarPdf('Especialidad')"/>
<input type="button" value="Exportar Word" class=" btn btn-primary" 
       onclick="ExportarWord()"/>
<input type="button" value="Imprimir" class=" btn btn-secondary" 
       onclick="Imprimir()" />
<br />
<form asp-controller="Especialidad" asp-action="Index" method="post" class=" mb-2"
      style="display:grid; grid-template-columns:1fr 1fr 1fr 1fr" id="frmFormulario">
    @*Filtro*@
    <label>Ingrese nombre de especialidad</label>
    <input type="text" id="nombre" class="form form-control" name="Nombre" value="@nombreEspecialidad" />
    <input type="submit" value="Buscar" class="btn btn-info" />
    <input type="button" value="Limpiar" class="btn btn-danger" onclick="Limpiar()" />
</form>

<form asp-controller="Especialidad" asp-action="Exportar" id="frmReporte">
    <table class="table" id="table">       
        @*<a asp-action="ExportarExcel" asp-controller="Especialidad">Exportar Excel</a>*@
        <thead class="thead-dark">
            <tr>
                <th>@Html.DisplayNameFor(x => x.IdEspecialidad)</th>
                <th>@Html.DisplayNameFor(x => x.Nombre)</th>
                <th>@Html.DisplayNameFor(x => x.Descripcion)</th>
                <th><strong>Operaciones</strong></th>
            </tr>
            <tr id="tcheck">
                <th>
                    <input type="checkbox" checked name="nombreProp" value="IdEspecialidad" />
                    <input type="hidden" name="tipoReporte" id="tipoReporte"/>
                </th>
                <th>
                <input type="checkbox" checked name="nombreProp" value="Nombre" />
                </th>
                <th>
                <input type="checkbox" checked name="nombreProp" value="Descripcion" />
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (EspecialidadCLS oEspecialidad in Model)
            {
                <tr>
                    <td>@oEspecialidad.IdEspecialidad</td>
                    <td>@oEspecialidad.Nombre</td>
                    <td>@oEspecialidad.Descripcion</td>
                    <td>
                        <i class="fa fa-trash btn btn-danger" aria-hidden="true"
                           onclick="EliminarEspecialidad(@oEspecialidad.IdEspecialidad)">
                        </i>
                        <a class="fa fa-edit btn btn-primary" aria-hidden="true"
                           asp-controller="Especialidad" asp-action="Editar"
                           asp-route-id="@oEspecialidad.IdEspecialidad">                              
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

<form asp-action="Eliminar" asp-controller="Especialidad" method="post" id="frmEnviarEliminar">
    <input type="hidden" id="txtIdEspecialidad" name="IdEspecialidad"/>
</form>

<script src="~/js/generic.js"></script>
<script src="~/js/sweetalert.js"></script>

<script>    
    function Limpiar() {
        document.getElementById("nombre").value = "";
        document.getElementById("frmFormulario").submit();
    }  

    //Eliminación lógica
    function EliminarEspecialidad(IdEspecialidad) {
        //alert(IdEspecialidad);
        document.getElementById("txtIdEspecialidad").value = IdEspecialidad;
        mostrarModal().then(res => {
            if (res.value) {
                var frmEnviarEliminar = document.getElementById("frmEnviarEliminar");
                frmEnviarEliminar.submit();
            }                
        })
    }
</script>