Models/Pagina.cs
using System;
using System.Collections.Generic;

namespace AppReportes.Models
{
    public partial class Pagina
    {
        public Pagina()
        {
            TipoUsuarioPagina = new HashSet<TipoUsuarioPagina>();
        }

        public int Iidpagina { get; set; }
        public string Mensaje { get; set; }
        public string Accion { get; set; }
        public string Controlador { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<TipoUsuarioPagina> TipoUsuarioPagina { get; set; }
    }
}

Controllers/PaginaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AppReportes.Clases;
using AppReportes.Models;

namespace AppReportes.Controllers
{
    public class PaginaController : Controller
    {
        public IActionResult Index(PaginaCLS paginaCLS)
        {
            List<PaginaCLS> listaPagina = new List<PaginaCLS>();
            using (BDHospitalContext db = new BDHospitalContext())
            {
                if(paginaCLS.Mensaje == null || paginaCLS.Mensaje == "")
                {
                    listaPagina = (from pagina in db.Pagina
                                   where pagina.Bhabilitado == 1
                                   select new PaginaCLS
                                   {
                                       IdPagina = pagina.Iidpagina,
                                       Mensaje = pagina.Mensaje,
                                       Accion = pagina.Accion,
                                       Controlador = pagina.Controlador
                                   }).ToList();
                    ViewBag.Mensaje = "";
                }
                else
                {
                    listaPagina = (from pagina in db.Pagina
                                   where pagina.Bhabilitado == 1
                                   && pagina.Mensaje.Contains(paginaCLS.Mensaje)
                                   select new PaginaCLS
                                   {
                                       IdPagina = pagina.Iidpagina,
                                       Mensaje = pagina.Mensaje,
                                       Accion = pagina.Accion,
                                       Controlador = pagina.Controlador
                                   }).ToList();
                    ViewBag.Mensaje = paginaCLS.Mensaje;
                }
            }
            return View(listaPagina);  
        }

        //Mostrar el formulario
        [HttpGet]
        public IActionResult Agregar()
        {
            return View();
        }

        //Realiza la inserción de datos
        [HttpPost]
        public IActionResult Agregar(PaginaCLS oPaginaCLS)
        {
            try
            {
                using(BDHospitalContext db = new BDHospitalContext())
                {
                    if(!ModelState.IsValid)
                    {
                        return View(oPaginaCLS);
                    }
                    else
                    {
                        Pagina oPagina = new Pagina();
                        oPagina.Mensaje = oPaginaCLS.Mensaje;
                        oPagina.Controlador = oPaginaCLS.Controlador;
                        oPagina.Accion = oPaginaCLS.Controlador;
                        oPagina.Bhabilitado = 1;
                        db.Pagina.Add(oPagina);
                        db.SaveChanges();
                    }                   
                }
            }
            catch(Exception)
            {
                return View(oPaginaCLS);
            }
            return RedirectToAction("Index");
        }

        //Eliminación física
        [HttpPost]
        public IActionResult Eliminar(int IdPagina)
        {
            string Error;
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    Pagina oPagina = db.Pagina.Where(x => x.Iidpagina == IdPagina).First();
                    db.Pagina.Remove(oPagina);
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                Error = e.Message;
            }           
            return RedirectToAction("Index");
        }
    }
}

Views/Pagina/Agregar.cshtml
@model AppReportes.Clases.PaginaCLS

@{
    ViewData["Title"] = "Agregar";
}

    <h1>Agregar nueva página</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Agregar" asp-controller="Pagina" id="frmEnviar" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <div class="form-group">
                <label asp-for="Mensaje" class="control-label"></label>
                <input asp-for="Mensaje" class="form-control" />
                <span asp-validation-for="Mensaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accion" class="control-label"></label>
                <input asp-for="Accion" class="form-control" />
                <span asp-validation-for="Accion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Controlador" class="control-label"></label>
                <input asp-for="Controlador" class="form-control" />
                <span asp-validation-for="Controlador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Guardar" class="btn btn-primary" onclick="Abrir()"/>
                <a asp-action="Index" class="btn btn-danger">Regresar</a>
            </div>
        </form>
    </div>
</div>

<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script>
    function Abrir(){

        mostrarModal().then(res => {
            if (res.value) {

                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Views/Pagina/Index.cshtml
@model IEnumerable<AppReportes.Clases.PaginaCLS>
@using AppReportes.Clases;

@{
    ViewData["Title"] = "Index";
    string mensaje = ViewBag.Mensaje;
}

<a class="btn btn-primary" asp-controller="Pagina" asp-action="Agregar">Nuevo</a>
<form asp-controller="Pagina" asp-action="Index" method="post" class=" mb-2"
      style="display:grid; grid-template-columns:1fr 1fr 1fr 1fr" id="frmFormulario">
    @*Filtro*@
    <label>Ingrese mensaje</label>
    <input type="text" id="MensajeDatos" class="form form-control" name="Mensaje"
           value="@mensaje" />
    <input type="submit" value="Buscar" class="btn btn-info" />
    <input type="button" value="Limpiar" class="btn btn-danger" onclick="Limpiar()" />
</form>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPagina)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mensaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Accion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Controlador)
            </th>
            <th><strong>Operaciones</strong></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPagina)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mensaje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Accion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Controlador)
                </td>
                <td>
                    <i class="fa fa-trash btn btn-danger" aria-hidden="true"
                       onclick="EliminarPagina(@item.IdPagina)">
                    </i>
                </td>
            </tr>
        }
    </tbody>
</table>

<form asp-action="Eliminar" asp-controller="Pagina" method="post" id="frmEliminarPagina">
    <input type="hidden" id="txtPagina" name="IdPagina"/>
</form>

<script src="~/js/generic.js"></script>
<script src="~/js/sweetalert.js"></script>>
<script>
    function Limpiar() {
        document.getElementById("MensajeDatos").value = "";
        document.getElementById("frmFormulario").submit();
    }

    //Eliminación física
    function EliminarPagina(IdPagina) {
        document.getElementById("txtPagina").value = IdPagina;
        mostrarModal().then(res => {
            if (res.value) {
                var frmEliminarPagina = document.getElementById("frmEliminarPagina");
                frmEliminarPagina.submit();
            }
        })
    }
</script>