Models/Medicamento.cs
using System;
using System.Collections.Generic;

namespace AppReportes.Models
{
    public partial class Medicamento
    {
        public Medicamento()
        {
            CitaMedicamento = new HashSet<CitaMedicamento>();
        }

        public int Iidmedicamento { get; set; }
        public string Nombre { get; set; }
        public string Concentracion { get; set; }
        public int? Iidformafarmaceutica { get; set; }
        public decimal? Precio { get; set; }
        public int? Stock { get; set; }
        public string Presentacion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual FormaFarmaceutica IidformafarmaceuticaNavigation { get; set; }
        public virtual ICollection<CitaMedicamento> CitaMedicamento { get; set; }
    }
}

Controllers/MedicamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AppReportes.Clases;
using AppReportes.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Cryptography.X509Certificates;

namespace AppReportes.Controllers
{
    public class MedicamentoController : Controller
    {
        public string Error = "Ha ocurrido una excepción, favor intente de nuevo";

        public List<SelectListItem> ListarFormaFarmaceutica()
        {            
            List<SelectListItem> selectLists = new List<SelectListItem>();
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    selectLists = (from ff in db.FormaFarmaceutica
                                   where ff.Bhabilitado == 1
                                   select new SelectListItem
                                   {
                                       Text = ff.Nombre,
                                       Value = ff.Iidformafarmaceutica.ToString()
                                   }).ToList();
                    selectLists.Insert(0, new SelectListItem
                    {
                        Text = "--Seleccione--",
                        Value = ""
                    });
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            return selectLists;
        }

        public IActionResult Agregar()
        {
            //Siempre para pasar un ComboBox a la vista se hace un ViewBag
            ViewBag.ListaFormaFarmaceutica = ListarFormaFarmaceutica();
            return View();
        }

        //Recuperar información para el combo box
        [HttpGet]
        public IActionResult Editar(int id)
        {
            MedicamentoCLS oMedicamentoCLS = new MedicamentoCLS();
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    oMedicamentoCLS = (from m in db.Medicamento
                                       where m.Iidmedicamento == id
                                       select new MedicamentoCLS
                                       {
                                           IdMedicamento = m.Iidmedicamento,
                                           Nombre = m.Nombre,
                                           Concentracion = m.Concentracion,
                                           IdFormaFarmaceutica = m.Iidformafarmaceutica,
                                           Precio = m.Precio,
                                           Stock = m.Stock,
                                           Presentacion = m.Presentacion
                                       }).First();
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            //Siempre para pasar un ComboBox a la vista se hace un ViewBag
            ViewBag.ListaFormaFarmaceutica = ListarFormaFarmaceutica();
            return View(oMedicamentoCLS);
        }

        //Metodo para editar un combo box
        [HttpPost]
        public IActionResult Agregar(MedicamentoCLS medicamentoCLS)
        {
            string NombreVista = "";
            try
            {
                using(BDHospitalContext db = new BDHospitalContext())
                {
                    if (medicamentoCLS.IdMedicamento == 0) NombreVista = "Agregar";
                    else NombreVista = "Editar";

                    if (!ModelState.IsValid)
                    {
                        //Siempre para pasar un ComboBox a la vista se hace un ViewBag
                        ViewBag.ListaFormaFarmaceutica = ListarFormaFarmaceutica();
                        return View(NombreVista, medicamentoCLS);
                    }
                    else
                    {
                        if(medicamentoCLS.IdMedicamento == 0)
                        {
                            Medicamento m = new Medicamento();
                            m.Nombre = medicamentoCLS.Nombre;
                            m.Concentracion = medicamentoCLS.Concentracion;
                            m.Iidformafarmaceutica = medicamentoCLS.IdFormaFarmaceutica;
                            m.Precio = medicamentoCLS.Precio;
                            m.Stock = medicamentoCLS.Stock;
                            m.Presentacion = medicamentoCLS.Presentacion;
                            m.Bhabilitado = 1;
                            db.Medicamento.Add(m);
                            db.SaveChanges();
                        }
                        else
                        {
                            Medicamento m = db.Medicamento
                                .Where(x => x.Iidmedicamento == medicamentoCLS.IdMedicamento).First();
                            m.Nombre = medicamentoCLS.Nombre;
                            m.Concentracion = medicamentoCLS.Concentracion;
                            m.Iidformafarmaceutica = medicamentoCLS.IdFormaFarmaceutica;
                            m.Precio = medicamentoCLS.Precio;
                            m.Stock = medicamentoCLS.Stock;
                            m.Presentacion = medicamentoCLS.Presentacion;
                            db.SaveChanges();
                        }
                    }
                }
            }
            catch(Exception)
            {
                return View(NombreVista, medicamentoCLS);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Index(MedicamentoCLS medicamentoCLS)
        {
            ViewBag.ListaForma = ListarFormaFarmaceutica();
            List<MedicamentoCLS> listaMedicamento = new List<MedicamentoCLS>();
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    if (medicamentoCLS.IdFormaFarmaceutica == null ||
                        medicamentoCLS.IdFormaFarmaceutica == 0)//Validacion ? en propiedades de tipo int y decimal
                    {
                        listaMedicamento = (from m in db.Medicamento
                                            join ff in db.FormaFarmaceutica
                                            on m.Iidformafarmaceutica equals ff.Iidformafarmaceutica
                                            where m.Bhabilitado == 1
                                            select new MedicamentoCLS
                                            {
                                                IdMedicamento = m.Iidmedicamento,
                                                Nombre = m.Nombre,
                                                Precio = (decimal)m.Precio,
                                                Stock = (int)m.Stock,
                                                NombreFormaFarmaceutica = ff.Nombre
                                            }).ToList();
                    }
                    else
                    {
                        listaMedicamento = (from m in db.Medicamento
                                            join ff in db.FormaFarmaceutica
                                            on m.Iidformafarmaceutica equals ff.Iidformafarmaceutica
                                            where m.Bhabilitado == 1
                                            && m.Iidformafarmaceutica == medicamentoCLS.IdFormaFarmaceutica
                                            select new MedicamentoCLS
                                            {
                                                IdMedicamento = m.Iidmedicamento,
                                                Nombre = m.Nombre,
                                                Precio = (decimal)m.Precio,
                                                Stock = (int)m.Stock,
                                                NombreFormaFarmaceutica = ff.Nombre
                                            }).ToList();
                    }
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            return View(listaMedicamento);
        }

        //Eliminacion fisica
        [HttpPost]
        public IActionResult Eliminar(int id)
        {
            try
            {             
                using(BDHospitalContext db = new BDHospitalContext())
                {
                    Medicamento oMedicamento = db.Medicamento.Where(x => x.Iidmedicamento == id).First();
                    db.Medicamento.Remove(oMedicamento);
                    db.SaveChanges();
                }
            }
            catch(Exception e)
            {
                Error = e.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Medicamento/Agregar.cshtml
@using AppReportes.Clases;
@model MedicamentoCLS; 
@{
    ViewData["Title"] = "Agregar";
    List<SelectListItem> lista = ViewBag.ListaFormaFarmaceutica;
}

<h1>Agregar medicamento</h1>
<hr />
<div class="row">
    <form asp-action="Agregar" asp-controller="Medicamento" id="frmEnviar" method="post">
        <div class="form-group">
            <label asp-for="Nombre"></label>
            <input type="text" class="form form-control" asp-for="Nombre" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Concentracion"></label>
            <input type="text" class="form form-control" asp-for="Concentracion" />
            <span asp-validation-for="Concentracion" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="IdFormaFarmaceutica"></label>
            <select asp-for="IdFormaFarmaceutica" class="form form-control"
                    asp-items="@lista"></select>
            <span asp-validation-for="IdFormaFarmaceutica" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Stock"></label>
            <input type="number" class="form form-control" asp-for="Stock" />
            <span asp-validation-for="Stock" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Precio"></label>
            <input type="text" class="form form-control" asp-for="Precio" />
            <span asp-validation-for="Precio" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Presentacion"></label>
            <input type="text" class="form form-control" asp-for="Presentacion" />
            <span asp-validation-for="Presentacion" class="text-danger"></span>
        </div>
        <div>
            <input type="button" value="Guardar" class="btn btn-primary"
                   onclick="Abrir()"/>
            <a class="btn btn-secondary" asp-action="Index" asp-controller="Medicamento">
                Regresar
            </a>
        </div>
    </form>
</div>
<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script>
    function Abrir() {
        mostrarModal().then(res => {
            if (res.value) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Views/Medicamento/Editar.cshtml
@using AppReportes.Clases;
@model MedicamentoCLS;
@{
    ViewData["Title"] = "Agregar";
    List<SelectListItem> lista = ViewBag.ListaFormaFarmaceutica;
}

<h1>Editar medicamento</h1>
<hr />
<div class="row">
    <form asp-action="Agregar" asp-controller="Medicamento" id="frmEnviar" method="post">
        <div class="form-group">
            <label asp-for="IdMedicamento"></label>
            <input type="text" class="form form-control" readonly asp-for="IdMedicamento" />
            <span asp-validation-for="IdMedicamento" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Concentracion"></label>
            <input type="text" class="form form-control" asp-for="Concentracion" />
            <span asp-validation-for="Concentracion" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="IdFormaFarmaceutica"></label>
            <select asp-for="IdFormaFarmaceutica" class="form form-control"
                    asp-items="@lista"></select>
            <span asp-validation-for="IdFormaFarmaceutica" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Stock"></label>
            <input type="number" class="form form-control" asp-for="Stock" />
            <span asp-validation-for="Stock" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Precio"></label>
            <input type="text" class="form form-control" asp-for="Precio" />
            <span asp-validation-for="Precio" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Presentacion"></label>
            <input type="text" class="form form-control" asp-for="Presentacion" />
            <span asp-validation-for="Presentacion" class="text-danger"></span>
        </div>
        <div>
            <input type="button" value="Guardar" class="btn btn-primary"
                   onclick="Abrir()" />
            <a class="btn btn-secondary" asp-action="Index" asp-controller="Medicamento">
                Regresar
            </a>
        </div>
    </form>
</div>
<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script>
    function Abrir() {
        mostrarModal().then(res => {
            if (res.value) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Views/Medicamento/Index.cshtml
@model IEnumerable<AppReportes.Clases.MedicamentoCLS>

@{
    ViewData["Title"] = "Index";
    List<SelectListItem> selectLists = ViewBag.ListaForma;
}

<a class="btn btn-primary" asp-controller="Medicamento" asp-action="Agregar">
    <strong>Agregar</strong>
</a>
<form style="display:grid; grid-template-columns: 1fr 2fr" class="mb-2" id="frmEnviar">
    <label>Ingrese nombre de la forma farmaceutica</label>
    @Html.DropDownList("IdFormaFarmaceutica", selectLists, new { @class = "form form-control" })
</form>

<table class="table">
    <thead class=" thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdMedicamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreFormaFarmaceutica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th><strong>Operaciones</strong></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdMedicamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreFormaFarmaceutica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
                <th>
                    <i class="fa fa-trash btn btn-danger" aria-hidden="true"
                       onclick="EliminarMedicamento(@item.IdMedicamento)">
                    </i>
                    <a class="fa fa-edit btn btn-primary" aria-hidden="true"
                       asp-controller="Medicamento" asp-action="Editar"
                       asp-route-id="@item.IdMedicamento">
                    </a>
                </th>
            </tr>
        }
    </tbody>
</table>
<form asp-action="Eliminar" asp-controller="Medicamento" method="post" id="frmEnviarEliminar">
    <input type="hidden" id="txtIdMedicamento" name="id" />
</form>

<script src="~/js/sweetalert.js"></script>
<script src="~/js/generic.js"></script>
<script>
    var IdFormaFarmaceutica = document.getElementById("IdFormaFarmaceutica");
    //Todo lo q seleccionas o escribas aqui, lo ejecuta(ComboBox)
    IdFormaFarmaceutica.onchange = function () {

        document.getElementById("frmEnviar").submit();
    }

    function EliminarMedicamento(IdMedicamento) {
        document.getElementById("txtIdMedicamento").value = IdMedicamento;
        mostrarModal().then(res => {
            if (res.value) {
                var frmEnviarEliminar = document.getElementById("frmEnviarEliminar");
                frmEnviarEliminar.submit();
            }
        })
    }
</script>